name: my-action

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world"
  echo-goodby:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I'll fail"
          exit 1
      - name: Say goodby
        run: echo "Goodby!"
