name: Slack test

on:
  push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send Slack notification
        uses: actions/slack-send-message@v3
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: '#afsal-test-channel'
          message: 'Workflow completed successfully!'